name: 'Build & Push Image'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghunt
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ GitHub.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
